name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        ruby: [ '3.4', '3.3', '3.2', '3.1' ]

    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install libsnappy-dev libzstd-dev
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: unit testing
      env:
        CI: true
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake test
